### ISSUE TITLE
createWrappedNode() seems to have broken?

### ISSUE THREAD

**Issue by gregjacobs** [dsherret/ts-morph#264]
Hey David,

Getting an error when trying to create wrapped nodes in 8.1.0

Example:

```ts
const fnExpr = /* get a ts.FunctionExpresion node instance here */

createWrappedNode( fnExpr );
```

I get the error:

```
Property '_tsSimpleAstBrand' is missing in type 'FunctionExpression'
```

**Comment by dsherret** [comment]
Hey Greg,

In version 7 the TypeScript peer dependency was dropped for this library because it was getting impossible to support multiple versions of the compiler. The compiler API can still be accessed though and you shouldn't experience any loss of functionality ([read more here}(https://github.com/dsherret/ts-simple-ast/blob/master/versions.md#version-7)).

That `_tsSimpleAstBrand` property exists to warn people about mixing their own version of the compiler with this library.

Sorry about the trouble here!

Basically you have two options...

**Option 1: Use the TypeScript compiler from the library (recommended)**

Drop the typescript dependency and change these two imports...

```ts
import * as ts from "typescript";
import Ast from "ts-simple-ast";
```

...to a single one...

```ts
import Ast, {SyntaxKind, ts} from "ts-simple-ast";
```

You could probably write a script using this library that modifies your project to that in case it's a lot to change.

**Option 2: Assert the node being passed into `createWrappedNode`**

Ensure you are using the same version of the TypeScript compiler that's used in this library and then assert the node being passed into `createWrappedNode` as `any` (or do some other assertion to maintain type safety):

```ts
import Ast, {createWrappedNode} from "ts-simple-ast";

const wrappedNode = createWrappedNode( fnExpr as any );
```

**Comment by gregjacobs** [comment]
Ah, very interesting David! Thanks for the workarounds. And great call on using the library to convert my imports :) I have about 130 files!

I've found that I need a mix of using the wrapped nodes and the raw TS nodes. The cases where the raw TS nodes come in is when I do tree transformation using `ts.visitEachChild()`, and synthesizing new nodes for replacements in the tree. Here's the article on where I learned this from btw in case you're interested: http://blog.scottlogic.com/2017/05/02/typescript-compiler-api-revisited.html

Perhaps if ts-simple-ast allowed for doing this kind of 'visitEachChild' transformation, I could drop the use of the raw TS nodes entirely. Any plans for that?

Also as a related point: when doing these `visitEachChild` transformations with synthesized nodes, I generally need to manually assign the `parent` property to the synthesized node. Perhaps your version of `visitEachChild` could handle that automatically.
