### ISSUE TITLE
The best way to grab the raw value of a declaration?

### ISSUE THREAD

**Issue by lazarljubenovic** [dsherret/ts-morph#289]
Say I have the following source.

```ts
const a = {
  foo: 1,
  bar: 2,
}
```

I can get the `ObjectLiteralExpression` whose `getText()` returns `'{\n foo: 1,\n bar: 2,\n}'`. To get the raw value of the object (not a compiler node), I could do `eval`. 

But this brings to question, what if not everything is a constant? What if we have the following:

```ts
const foo = 1
const bar = 2
const a = { foo, bar }
```

If I `eval` now, I'll get either get an error or whatever `foo` and `bar` are in the scope of my _compiler_'s code.

The problem gets even more complex when some of these are imports.

```ts
// file.ts
export const foo = 1
export const bar = 2

// main.ts
import {foo, bar} from './file'
const a = {foo, bar}
```

I'd like to be able to get the _object_ (not its node) `{foo: 1, bar: 2}` in all three cases. Is this even in the scope of the library? Is it common that a compiler wants to read the values as-is from the code it traverses? 

I'm trying to build a small framework and I specify a template definition as an object which I pass to a decorator:

```ts
import { NodeType } from './node-types'
@Template([
  { type: NodeType.Html, tagName: 'div', children: [
    { type: NodeType.Html, tagName: 'span', children: [
      { type: NodeType.Text, content: `Hello!` }
    ] }
  ] }
])
export class Component { }
```

I use this module becase I want to generate code which will handle the bindings on the template, but I want to use the template-definition object as-is. 

A temporary workaroun that I have is to ditch the `NodeType` as an enum, use a string instead and use simple strings. Then I could safely "eval" (although it still feels dirty -- having a valid JSON string and then just parsing it feels nicer somehow).

Thanks!

**Comment by dsherret** [comment]
Hey @lazarljubenovic, it's definitely in scope for this library, but it is challenging!

You could get the properties of the `ObjectLiteralExpression` (`.getProperties()`) and for each `PropertyAssignment` get the initializer. From there, you'll need to inspect the initializer to see what it is. 

**For the initializer...**

If it's a string literal, then call `.getLiteralValue()` on it. Done.

Otherwise... get the name identifier...

* If the initializer is a `PropertyAccessExpression`, then get the name node (`.getNameNode()`).
* If the initializer is an `Identifier`, you can use that.

**For an identifier and `PropertyAccessExpression`'s name...**

One you have the identifier, call `.getDefinitions()` on it ("go to definition"). From there, call `.getNode()` on the results and see if you can get something with an initializer. From there, repeat the steps above for the initializer.

Let me know if you would like me to go into more detail or if you have any questions.

**Comment by lazarljubenovic** [comment]
Thanks a lot for the detailed explanation! It helped me understand the general direction of the flow and get a better overview of how things are expected to be done. Also, didn't know about `getDefinitions`. Why is it plural? Don't we know it has to be exactly one? I'm aware that two things with the same name can coexist in a project, but by knowing what kind of thing something is and by following import paths, doesn't it always resolve to a single thing? 

It indeed is more complex than I hoped. Funny how static analysis opens up amazing possibilities, but you lose things you took for granted when writng code and not caring for the mechanics under the hood.

I've solved my specific troubles firstly by using a JSON string intead of an object, and soon swapped it with a proper HTML-like compiler. :sparkles:

**Comment by dsherret** [comment]
@lazarljubenovic it's plural because it's possible to have multiple declarations with the same name (new method is still plural `.getDefinitionNodes()` too). For example:

```ts
function SameName() {
}
namespace SameName {
}
interface SameName {
}
```

Anyway, I'm glad you solved the problem!

**Comment by dsherret** [comment]
Closing this. Let me know if you have any other questions or if I missed answering something.

**Comment by DanielOrtel** [comment]
In case anyone stumbles on it in the future, I've written a gist for this: https://gist.github.com/DanielOrtel/d258d2cf2af0cb3d359a3fa1f1bd03f5

It's just a prototype implementation with quite a few limitations, namely function declarations are simply null-d and not handled and external imports(from node_modules, or outside the project scope) are also null-d, since I couldn't get their initializers, but in case you really need it, it's a decent starting point.

**Comment by benoitlahoz** [comment]
Thank you @DanielOrtel for this gist.

I added some options for `ShorthandPropertyAssignment`, `NoSubstitutionTemplateLiteral` and `TypeReference`:

```typescript
// ...

case SyntaxKind.ShorthandPropertyAssignment:
   return resolveShorthandProperty(input, project);
case SyntaxKind.NoSubstitutionTemplateLiteral:
   return input.getLiteralValue();
case SyntaxKind.TypeReference:
  return;

// ...

function resolveShorthandProperty(
  shorthand: ShorthandPropertyAssignment,
  project: Project
): any {
  const references = shorthand.findReferences();
  let declaration: Node | undefined;

  if (references.length > 0) {
    declaration = references[0].getDefinition().getDeclarationNode();
  }

  if (declaration) {
    return reducePropertyToPrimitive(declaration, project);
  }

  return null;
}
```

Your gist is so helpful! I guess you could publish a package with it 🥇 
Thank you.

**Comment by DanielOrtel** [comment]
@benoitlahoz sure thing, here you go: https://www.npmjs.com/package/ts-morph-utils 

Since I wrote that specific gist, I've expanded on it a little bit and added more utilities that I needed, which is why I chose a more generic name for the package. You're looking for `morphDeclarationToRaw` from the package. Check the `Usage` section on how to use it. 

There's also utilities for writing the object back to file, along with handling values for imports from node modules. 

In case there's still cases missing that you need, feel free to open a PR.
