### ISSUE TITLE
_tsSimpleAstBrand and import typescript directly

### ISSUE THREAD

**Issue by cancerberoSgx** [dsherret/ts-morph#333]
This is a question about the copy of typescript.d.ts inside simple-ast and basically the _tsSimpleAstBrand member: 

```
  /**
    * This brand prevents using nodes not created within this library or not created within the ts namespace object of this library.
    * It's recommended that you only use this library and use its ts named export for all your TypeScript compiler needs.
    * If you want to ignore this and are using the same TypeScript compiler version as ts.versionMajorMinor then assert it to ts.Node.
    * If you don't use this library with this same major & minor version of TypeScript then be warned, you may encounter unexpected behaviour.
    */
  _tsSimpleAstBrand: undefined;
```

First, I would like to make sure I understand correctly. 

Is the idea that in my project I always reference the typescript native types declared on your library, and is not advisable to import typscript's declarations never ? Something like: 

`import {  ts } from 'ts-simple-ast';`

instead of : 

`import * as ts from 'typescript'`

??

I would like to document this better in https://dsherret.github.io/ts-simple-ast/navigation/compiler-nodes so I want to make sure i got it. 

Second, my opinion, 

 * Is it really necessary that simple-ast duplicate and export typescript's decls? 
 * Why couldn't just use user's typescript version? (he will be responsible). 
 * once the user enters in the "compiler world" (using compilerX member) then is up to him and **he will be responsible of that code and of the typescript version**.

 Two (bad) experiences: 

 * I wanted to run / compile my simple-ast based code using typescript 3.0 and for the particular thing I wanted to try (new things) it was not possible (only casting to "any" I was able to compile)

 * some things are in simple-ast ts namespace and other are not and this seems to be arbitrary. for example, SyntaxKind is not in ts, ClassDeclaration and Node are on . If the idea is that users work this way the code will be hard to maintain and understand...

 (the last one was just my opinion, I think I want to know the reason you were forced to do this)

 thanks

**Comment by dsherret** [comment]
> Is the idea that in my project I always reference the typescript native types declared on your library, and is not advisable to import typscript's declarations never ?

Yup. I highly recommend not using an imported version of TypeScript because it will most likely lead to bugs if the versions aren't the same.

> Is it really necessary that simple-ast duplicate and export typescript's decls?

Several reasons:

* There are very often breaking changes in the compiler API.
* Previously when this library referenced Compiler API declarations in its declaration file, that would throw compile errors when the user didn't have something this library referenced (ex. user is using TS 2.5 and this library's declaration file is referencing `ts.JSXFragment` found in 2.6... well now that's a compile error for the user)
* There may be incompatibilities with ts-simple-ast depending on newer features not found in the version of the typescript compiler you are depending on.
* Sometimes people may want to use an old version of the compiler to compile their code and if this library didn't support that version then that would be a problem.
* Means I only have to support one version of the compiler (way less maintenance)
* Allows me to pull out commonly used parts of the compiler API to `ts-simple-ast` to make it easier to use (more on that later)

Previously this library had a peer dependency on the typescript compiler API and it caused all sorts of problems. Bringing it into this library solved all these situations.

> Why couldn't just use user's typescript version? (he will be responsible).

The user is not always responsible ;)

> I wanted to run / compile my simple-ast based code using typescript 3.0 and for the particular thing I wanted to try (new things) it was not possible (only casting to "any" I was able to compile)

This is a very rare edge case. I would recommend checking out the library and then updating the library yourself and use that. You'll need to run the `createCompilerApiLayer` function to regenerate the compiler api declarations after updating (then you can use `npm run package`—command I just added—to build and create the declaration file for the app). I tried doing it right now and ran into some differences with the latest "@next" version not working the same way as the current version (reinforcing my point on why this library only depends on one version of the compiler).

> some things are in simple-ast ts namespace and other are not and this seems to be arbitrary. for example, SyntaxKind is not in ts, ClassDeclaration and Node are on . If the idea is that users work this way the code will be hard to maintain and understand...

When using ts-simple-ast, the library itself is first class and the compiler API is secondary. SyntaxKind is pulled out because it is used often in the library. `ClassDeclaration` is not because you should be using the wrapped `ClassDeclaration` that the library exposes. In your case, you're approaching using this library from using the compiler API, but most people approach it from no experience with anything and so it's more geared towards those people.

**Comment by cancerberoSgx** [comment]
Thank you very much for the detailed explanation. Glad to know you already walked the path of depending on imported typescript and know the consequences! I have some replies but better leave them till tomorrow. Thanks again, great work! I'm following progress on ts team but seems only recently they have payed more attention to compiler API but still very little for my taste. For example they are just implementing file move refactor while you already have it here. This is exiting! thanks!

P/D in my case is worst than using the compiler API, i'm trying to integrate this with language service plugins - so far so good. But still much to learn. thakns

**Comment by dsherret** [comment]
Updated the documentation. Closing this issue.
