### ISSUE TITLE
Documentation Update: How to use with webpack loaders?

### ISSUE THREAD

**Issue by couchcrew-thomas** [dsherret/ts-morph#396]
Is it possible to integrate this within a webpack build?
The ts-loader / awesome-typescript-loader support custom compilers, but this setting is explained nowhere.

If it is possible can you please document how to do it?

**Comment by couchcrew-thomas** [comment]
Thanks for your reply. I was hoping it would support the same core API with an ability to add the ast manipulations.

I've already tried working with the transformation API, but its very cumbersome. E.g. I've managed to rename method declarations, but how to rename the calls of the same methods eludes me.

Are you using the transformation API as an entry point for your library or do you go a different path? It would be awesome if this library could be hooked into the transformation process.

**Comment by lazarljubenovic** [comment]
An idea which was wondering around my mind for some time, and could be
relevant now: Would a functional API be possible for this module? Could we
have something like a ts-simple-api/fp which just gives you helper
functions?

**Comment by dsherret** [comment]
I don't believe the transformation api has the language service/symbols available so it would be difficult to figure out how to rename everything at that point.

No, I'm not using the transformation API anywhere in the library.

@lazarljubenovic I think using and developing on something like https://github.com/ajafff/tsutils would be more appropriate for that?

Anyway, closing this issue. The way that this library is currently structured makes it difficult to integrate with something like webpack. What could be done is instead of using the typescript compiler to emit, this project could be used. For example:

```ts
const project = new Project({ tsConfigFilePath: "tsconfig.json" });

// ...do all your manipulations here without saving...

// ...optionally check diagnostics...

// emit
project.emit();
```
