### ISSUE TITLE
Ability to get results of forEachChild as an array

### ISSUE THREAD

**Issue by dsherret** [dsherret/ts-morph#514]
This would probably be called `forEachChildAsArray()` for discoverability and be implemented like so:

```ts
const children: Node[] = [];
node.forEachChild(child => {
    children.push(child);
});
return children;
```

**Comment by dsherret** [comment]
This is a sad name, but considering the compiler API design I think it's necessary.

**Comment by dsherret** [comment]
For some reason this was not merged to master. Reopen and investigate what else might be missing during that time.

**Comment by cancerberoSgx** [comment]
When coding https://github.com/dsherret/ts-morph/pull/584 I had an idea for methods related to children. If we want to give support to both getChildren modalities (getChildren and forEachChild) and don't introduce methods, this could be an alternative: add a optional boolean parameter `asForEachChild` that , if true, the method obtain children using forEachChild instead of getCihldren. This way we don't have to create new (probably ugly) method names, signatures are still backguards compatible and I think is more intuitive for users. This should be done for all Node methods related to children: getChildren, getChildIndex, getIndexOfChild, getChildAtIndex, etc... Example: 

```ts
   /**
     * Gets all the children of the node.
     * @param asForEachChild - If true, `forEachChild` method will be used to obtain children. Otherwise `getChildren` will be used.
     */
    getChildren(asForEachChild?: boolean): Node[] {
        return (asForEachChild ? this._getCompilerForEachChildren() : this._getCompilerChildren())
            .map(n => this._getNodeFromCompilerNode(n));
    }

    /**
     * Gets the child at the specified index.
     * @param index - Index of the child.
     * @param asForEachChild - If true, `forEachChild` method will be used to obtain children. Otherwise `getChildren` will be used.
     */
    getChildAtIndex(index: number, asForEachChild?: boolean): Node {
        return this._getNodeFromCompilerNode(asForEachChild ? this._getCompilerForEachChildAtIndex(index) :  this._getCompilerChildAtIndex(index));
    }
```

**Comment by dsherret** [comment]
Thanks for your input again! In scenarios like this, my preference is to add new methods for different behaviours rather than changing behaviour based on a boolean parameter (also, see my comment [here](https://github.com/dsherret/ts-morph/issues/513#issuecomment-476016881) on why I try to stay away from boolean parameters). The name `forEachChildAsArray` is also used because the `forEachChild` prefix offers better discoverability in autocomplete since the results show up next to each other.

**Comment by cancerberoSgx** [comment]
Understandable. 

Also in Node.js there is an internal one called _getCompilerForEachChildren - this is, getForEachChildren could be another option although it doesn't source nice. 

I like to name new things, but in this case, I wouldn't like to be in your shoes :P . 

My two cents

**Comment by dsherret** [comment]
Going with `forEachChildAsArray` for discoverability. Problem here was I accidentally committed to a different branch other than `dev`.
