### ISSUE TITLE
Inserting at specific position

### ISSUE THREAD

**Issue by tiehm** [dsherret/ts-morph#565]
Hello! I am trying to insert some code at a specific position within a method, however, I have no idea if it is possible and if so; how?

**Comment by Gerrit0** [comment]
You probably want `addStatements`, or `insertText` - https://dsherret.github.io/ts-morph/manipulation/#adding-inserting-and-removing-statements

**Comment by tiehm** [comment]
Thanks! 

Is it also possible to get the position of one specific statement within a method?

**Comment by dsherret** [comment]
@tiehm yeah, call `.getChildIndex()` on the statement.

@Gerrit0 thanks for answering!

**Comment by tiehm** [comment]
Thank you. I only have one issue now, how would I use something like `<ClassDeclaration>.getMethod('run').getStatement(fn)`
I wonder what `fn` would have to get `await func(x)` from 
```
class Y {

    public async run() {
        await func(x);
    }

}
```

**Comment by dsherret** [comment]
It depends how you want to find that statement. I recommend using https://ts-ast-viewer.com to see what the statements look like, but one example would be to do:

```ts
const awaitStatement = runMethod.getStatement(statement => TypeGuards.isExpressionStatement(statement) && TypeGuards.isAwaitExpression(statement.getExpression()));
```

Note: I just opened #567, which will make `.getStatement` a little better.

**Comment by tiehm** [comment]
Is there also the possibility to detect comments and get their index?

**Comment by dsherret** [comment]
There are the methods `.getLeadingCommentRanges()` and `.getTrailingCommentRanges()` on every node. Comments aren't part of the AST though so that makes them a little difficult to work with (they won't have an index). Read more here: https://github.com/Microsoft/TypeScript/wiki/Architectural-Overview#trivia

If there's a scenario you think one of the methods isn't handling comments well enough then please let me know. I feel like there needs be some way of specifying that a statement should be inserted before or after a comment, but I'm not sure about a good way of doing that.

**Comment by tiehm** [comment]
So I guess the best method to get the index of a specific comment (by content) I would have to get the index in the `bodyText`.

**Comment by dsherret** [comment]
@tiehm in ts-morph 2.0 certain comments will be returned when calling `#getStatementsWithComments()`. When inserting, the index will be based on the index in that array. It will allow you to insert before or after comments that are on a line by themselves. See #575 for more detail.

I believe this is resolved now.
