### ISSUE TITLE
Ability to use TS-Morph as Language server? 

### ISSUE THREAD

**Issue by Morphexe** [dsherret/ts-morph#611]
I am not sure if I am misunderstanding and  my lack of knowledge is not helping.
 
Basically I want to use this to facilitate the use of refactors and intellisense in vscode or event to create language service plugins to fix.

The way I see this is to re-implement a language server using ts-morph  as supported - I was trying to avoid this.

Somehow link ts-morph and the current tsserver so I don't have to parse the source files twice?

Any ideas? I Might be missing something really obvious though :\

**Comment by dsherret** [comment]
Hey @Morphexe, sorry for my delay in responding. See #326... in summary: this isn't possible at the moment.

**Comment by Morphexe** [comment]
@dsherret No need for apologies! :) 
Any idea on where to start if something like this would be possible? Any problems you  foresee  if I were to use ts-morph as a separate language server?

**Comment by dsherret** [comment]
It's not really designed for that at the moment so it would require a huge redesign that would touch a lot of the internals.

I'm not sure about what problems there could be for using it as a separate language server because I don't really have any experience with that. It seems a major issue is that it will be inefficient as @cancerberoSgx noted in that referenced issue.

Closing this. Follow #326 for updates.
