### ISSUE TITLE
How to replace PropertyAccessExpression

### ISSUE THREAD

**Issue by nchanged** [dsherret/ts-morph#637]
HI! I've read everything, and checked every related issue, but couldn't find an answer to this:
I am trying to replace a PropertyAccess expression with a single variable (or a string). For example:

Having a source
```ts
console.log(foo.bar)
```

The objective is to replace foo.bar with just a string to it looks like

```ts
console.log("something")
```

Trying this:

```ts
 const Identifiers = testFile.getDescendantsOfKind(ts.SyntaxKind.PropertyAccessExpression);
  Identifiers.forEach(id => {

    if (id.getText() === 'foo.bar') {
       id.replaceWIthText // -> doesn't work
       id.rename // nope
       id.set // doesn't work either 
    }
})
```

How one would do that? 
Thanks

**Comment by dsherret** [comment]
Hey @nchanged, doing `id.replaceWithText(`"something"`)` should work. If not, let me know.

**Comment by nchanged** [comment]
```
errors/classes/BaseError.js:8
        var _this = _super.call(this, message) || this;
                           ^
Error: Attempted to get information from a node that was removed or forgotten.
```
Nope, won't work

**Comment by dsherret** [comment]
@nchanged it's helpful to provide reproducible snippets of code when you get errors.

Are you sure it's the `replaceWithText` line erroring? Looks like there's a node being used that doesn't exist anymore.

Is your code doing something like this?

```ts
id.replaceWithText(`"something"`);
// do something else with id
console.log(id.getText());
```

If so, that doesn't work because `id` was replaced with new node (it's no longer an identifiery for example). Ensure something like this is done:

```ts
const newNode = id.replaceWithText(`"something"`);
console.log(newNode.getText());
```

**Comment by nchanged** [comment]
@dsherret just tried with 1 member it works fine, however:


```
const Identifiers = testFile.getDescendantsOfKind(ts.SyntaxKind.PropertyAccessExpression);
  Identifiers.forEach(id => {
    if (id.getText() === 'foo.bar.oi') {
      id.replaceWithText('oi');
    }
  });
```

and the contents:

```
console.log(foo.bar.oi);
```

throws the above-mentioned error.

**Comment by dsherret** [comment]
Oh right! I forgot about the code in the original post. That's because after calling `replaceWithText` on that node, the `bar` and `oi` nodes will no longer be in the source file, but they'll still be in the array of `Identifiers`. In other words, it's visiting the node `foo.bar.oi` first then visiting `bar.oi` after.

To solve this, you just need to check `id.wasForgotten()` before doing anything else. Alternatively, you could navigate the tree in post order, but that's not supported easily until #533 is implemented.

**Comment by nchanged** [comment]
Nice!!!
```
if (!id.wasForgotten()) {
      if (id.getText() === 'foo.bar.oi') {
        id.replaceWithText('oi');
      }
    }
```

did the trick! Thanks for such an awesome lib!!
I have a few more questions, I will create an issue a bit later ;-) Thanks again!
