### ISSUE TITLE
How to get the ast-json from ast-node

### ISSUE THREAD

**Issue by starFelix** [dsherret/ts-morph#643]
I'm very sorry that ask a question which is not report a bug.
I want to get the ast-json from ast-node. 
But I didn't find anyway to do it simple.

**Comment by dsherret** [comment]
@starFelix that's fine! Lots of questions on here and I prefer questions being asked in the issue tracker.

So you're wondering how to take a node and get a json representation from it? Do you need to reload it after it's been serialized? What's the purpose for converting it to json? I'm trying to understand the use case.

So it's kind of difficult to serialize the wrapped nodes because they have a lot of internal references. The same is true for the underlying node from the compiler api and they have a lot of internal state as well.

If you really want to serialize something, it's probably best to serialize the underlying compiler node (`node.compilerNode`) using something like [circular-json](https://github.com/WebReflection/circular-json) because there will occasionally be circular references.

**Comment by starFelix** [comment]
hi, @dsherret ,thanks for your answer.

**Comment by dsherret** [comment]
@starFelix by ast-viewer do you mean ts-ast-viewer.com? If so, try opening the options and disable binding and using ts-creator... then try pasting in the text. That might lower the amount of work it has to do enough so that it doesn't get stuck.

Yeah, I think using circular-json on the `node.compilerNode` should get what you need.

**Comment by starFelix** [comment]
It works! Thank you.
