### ISSUE TITLE
getter refactoring.

### ISSUE THREAD

**Issue by wongchichong** [dsherret/ts-morph#645]
Should we refactor all those getXXX() { } functions into getter function like get XXX() { }

**Comment by dsherret** [comment]
Hey @wongchichong, I thought about doing that in the past and actually went to refactor the code once, but was quickly stopped in my tracks.

There are several advantages to using functions for this library rather than get accessors:

1. They can be parameterized if necessary and this is done in certain cases. I stopped the refactor to get accessors because I ran into a case where a method accepted arguments and thought it would be inconsistent to have some functionality on get accessors and others on methods. Now with using methods though, it's very easy to introduce new optional parameters without breaking everyone's existing code and having inconsistencies.
2. They don't give a false impression that the property can be accessed many times with no associated cost. For example it's way easier to write this...

    ```ts
    classDec.methods[0].setReturnType("string");
    classDec.methods[0].addParameter({ name: "p", type: "number" });
    ```

    ...compared to this...

    ```ts
    classDec.getMethods()[0].setReturnType("string");
    classDec.getMethods()[0].addParameter({ name: "p", type: "number" });
    ```

    In the second example, it's more clear that for performance reasons the code should probably be:

    ```ts
    const methods = classDec.getMethods();
    methods[0].setReturnType("string");
    methods[0].addParameter({ name: "p", type: "number" });
    ```

    The following doesn't convey why the assignment to a local variable is done:

    ```ts
    const methods = classDec.methods;
    methods[0].setReturnType("string");
    methods[0].addParameter({ name: "p", type: "number" });
    ```

3. It alphabetically groups similar functionality together in code completion. For example, instead of `methods` being listed on `m`, it's listed on `getM` which groups it along with the `getMethod(...)` and `getMethodOrThrow(...)` methods. This helps people discover these other methods and might encourage them to use them more.
