### ISSUE TITLE
Support for Map

### ISSUE THREAD

**Issue by claudv** [dsherret/ts-morph#647]
Very nice project.

Just inquiring on the chance to see `Map<K,V>` supported any time soon?

**Comment by dsherret** [comment]
Hey @claudv, thanks! Are you having diagnostics (`project.getPreEmitDiagnostics()`) about the map type not existing?

To get that to work it's essentially the same as getting `Map` to work with the typescript compiler on its own—you can change the `target` property in the compiler options to `es2015`.

If you're specifying a tsconfig.json file in the project constructor then you can change the `target` compiler option in that file to `es2015`. Otherwise, the compiler option can be specified by doing:

```ts
import { Project, ScriptTarget } from "ts-morph";

const project = new Project({
    compilerOptions: {
        target: ScriptTarget.ES2015
    }
});
```

Another option is to change the `lib` compiler option to include "es2015" (see lib at https://www.typescriptlang.org/docs/handbook/compiler-options.html).

Let me know if I understood your question correctly and if that works.

**Comment by claudv** [comment]
Hey @dsherret, many thanks for the quick reply.

What I meant is the possibility to tell is a type is a map. 

The class `Type` has a number of convenience methods such as `isArray()` plus `getArrayElementType()` to inspect the contained type. 

I was wondering if we can have `Type.isMap()` with accessors for the underlying key/value types (eg `getMapKeyType()` and `getMapValueType())`.

If your answer already addressed this point I apologize for not understanding, I have just started to familiarize with the tool.

**Comment by dsherret** [comment]
@claudv ah, ok I see what you're asking. I just double checked and there is no special handling of the es2015 `Map` type in the compiler api so I probably won't add it to the library.

You could create your own function for checking if the type is the `Map` type. I believe this should be sufficient:

```ts
function isMapType(type: Type) {
    const symbol = type.getSymbol();
    if (symbol == null)
        return false;
    return symbol.getFullyQualifiedName() === "Map";
}
```

Then you can get the key and value from the type arguments:

```ts
if (isMapType(type)) {
    const typeArgs = type.getTypeArguments();
    console.log("key: " + typeArgs[0].getText());
    console.log("value: " + typeArgs[1].getText());
}
```

**Comment by claudv** [comment]
@dsherret that should do, thank you very much for your help.
