### ISSUE TITLE
Parse text to node

### ISSUE THREAD

**Issue by furstenheim-geoblink** [dsherret/ts-morph#649]
Hi,
I'm not sure if this is possible. But I don't seem to find the way to do it.
How does one obtain a node from a string. Everything I read seems to point out that I should be writing a file to disk, which doesn't make much sense, I'd say.

Something like:

    const someString = 'Array<MyClass>'
    const node = project.Parse(someString)

My usecase is a plugin for https://github.com/geoblink/apidoc-plugin-ts
It already has a parser which will pass to the plugin the slices of code in the definitions of the API. I'd like to be able to parse that.

Thanks

**Comment by dsherret** [comment]
Hey @furstenheim-geoblink,

Files aren't written to file system unless `.save()/.saveSync()` is called on the file, directory, or project. Until then everything stays in memory.

Regarding parsing strings like "Array<MyClass>" to a node, it's not always possible to parse nodes without some context. For example in this case, should that string be parsed as a type reference (ex. `let v: Array<MyClass>;`), a call expression (ex. `let v = new Array<MyClass>();`), or an expression with type arguments (ex. `class C extends Array<MyClass> {}`)? For this reason it's not really practical to create an API to parse a string to a node (though it is possible to use the scanner—`ts.createScanner`—to at least get the tokens).

The only thing that's possible with the compiler api is to parse the text to a source file then get out of it the information you need.

---

One thing you could do with ts-morph is create a source file in the project then delete it when you're done with it (or just never save). For example:

```ts
// as stated before: this file will never be written to the file system because
// it's not saved... this is all done in memory

const sourceFile = project.createSourceFile("__tempfile__.ts", "let v: Array<MyClass>;");
try {
    // do something with sourceFile here
} finally {
    sourceFile.delete();
}
```

The reason this should be done from the `project` object is because that will have all the lib files loaded, your settings, etc. I'm not entirely sure about your use case though, but there might be something better and perhaps if you just need parsing then you may want to use the compiler api directly.

**Comment by furstenheim-geoblink** [comment]
@dsherret Thanks a lot! that was pretty clear
