### ISSUE TITLE
Type compatibility 

### ISSUE THREAD

**Issue by DanTsk** [dsherret/ts-morph#739]
Is there any way to check that two types are compatible? For example, when object literal compatible with interface definition in function argument.

**Comment by DanTsk** [comment]
Like this. 
```
interface Named {
    name: string;
}

class Person {
    name: string;
}

let p: Named;
// OK, because of structural typing
p = new Person();
```
Is there any function/util to check that `Person` and `Named` types are compatible?

**Comment by dsherret** [comment]
See #357. Basically no because the compiler API does not expose that yet.

**Comment by ChristianIvicevic** [comment]
Just chiming in to the question since I was curious. @DanTsk What is your actual intention with that compatibility check? Types in TS are transparent by default and Microsoft unfortunately hasn't implemented a dedicated `opaque` keyword. If you want to prevent this semantically wrong assignment in code, so even before the comparison of it, you can use a helper such as this:

```typescript
type Opaque<T> = T & { readonly __opaque: unique symbol };
```
