### ISSUE TITLE
get wrapped node from compiler node

### ISSUE THREAD

**Issue by ooyyloo** [dsherret/ts-morph#768]
I want to remove some nodes. I know the "remove" method only exists in wrapped node. Now I have a compiler node which is to be removed, but I don't know the way to get the wrapped node from a compiler node. I've tried "createWrappedNode" to get the wrapped node, but when it calls "remove" method, errors occurred. I want to know whether there is a way to get the removable wrapped node from a compiler node.

**Comment by dsherret** [comment]
@ooyyloo does the compiler node come from a source file created with ts-morph?

When you're calling "remove" it's giving you an error saying you're not allowed to do that, right? That makes sense because ts-morph can't manipulate compiler nodes created outside of its controlled environment.

What I could do is add a `sourceFile.getNodeFromCompilerNode(compilerNode: ts.Node): Node` method, but it would require the compiler node to have come from a descendant of `sourceFile.compilerNode`.

**Comment by ooyyloo** [comment]
> @ooyyloo does the compiler node come from a source file created with ts-morph?
> 
> When you're calling "remove" it's giving you an error saying you're not allowed to do that, right? That makes sense because ts-morph can't manipulate compiler nodes created outside of its controlled environment.
> 
> What I could do is add a `sourceFile.getNodeFromCompilerNode(compilerNode: ts.Node): Node` method, but it would require the compiler node to have come from a descendant of `sourceFile.compilerNode`.

If you implement the function that returns the corresponding ts-morph symbol of compilerSymbol, that will better.

**Comment by dsherret** [comment]
@ooyyloo in this case, why wouldn't you have the symbol from ts-morph? (Why bother with compiler symbols?)

If the compiler symbols are being provided from another source other than a ts-morph project then I don't think it's possible to support that scenario. If they are from ts-morph, then why not just use wrapped symbols everywhere?

**Comment by ooyyloo** [comment]
> @ooyyloo in this case, why wouldn't you have the symbol from ts-morph? (Why bother with compiler symbols?)
> 
> If the compiler symbols are being provided from another source other than a ts-morph project then I don't think it's possible to support that scenario. If they are from ts-morph, then why not just use wrapped symbols everywhere?
> 
> Anyway, I'm trying to understand the use case.

I need to use some functions written in the source code of TypeScript. Some of the functions and varaibles are not exposed, but I need to change them to fit my requirement. My requirement is that outputing the all symbols that are accessed when using "getAliasedSymbol" function.

**Comment by phiresky** [comment]
I have the same issue for ts.Type => wrapped Type

I'm trying to get the structural property types of a inferred type, and the only way to do that is by using the internal `symbol.type` property. So now I have this code:

```ts
outerType
    .getProperties()
    .map((p) => [
        p.getName(),
        typeChecker._context.compilerFactory.getType((p.compilerSymbol as any).type as ts.Type).getText()
    ])
```

The `(p.compilerSymbol as any).type) as ts.Type)` is expected, but there's no way from what I can tell to wrap a ts.Type back into a Type wrapper without using the internal `._context.compilerFactory` property.

**Comment by dsherret** [comment]
@phiresky I believe that should be possible with the current api. If not please open up an issue for the API not supporting something. Really shouldn't be accessing the internal `_context` property as that is internal and thus extremely unstable.

> What's more, I need to do tree shaking(delete some nodes on the ast), which means I need ts-morph nodes to do the tree shaking.

I believe use the `transform` function found on nodes. Manually manipulating the underlying AST otherwise will lead to unexpected behaviour when using ts-morph.
