### ISSUE TITLE
How to get return type ?

### ISSUE THREAD

**Issue by yantrab** [dsherret/ts-morph#774]
I need help with that. how to get return type (User) of this function:

```
    getUser() {
        return new User({lastName: 'tra', firstName: 'yaya'});
    }
```

**Comment by dsherret** [comment]
@yantrab should just be the `#getReturnType()` method: `sourceFile.getClassOrThrow("YourClassName").getMethodOrThrow("getUser").getReturnType()`

**Comment by yantrab** [comment]
get Return Type not working in this case.

**Comment by dsherret** [comment]
@yantrab are there any diagnostics in `project.getPreEmitDiagnostics()`?

**Comment by yantrab** [comment]
@dsherret  you are right after set tsconfig file path, all right.
thanks a lot.

**Comment by dsherret** [comment]
@yantrab see here https://github.com/dsherret/ts-morph/issues/453#issuecomment-427405736

**Comment by yantrab** [comment]
@dsherret  this is my class:
```
@Controller("some")
export class SomeController {
    constructor(private someService: SomeService) {
    }
    @Get("user")
    getUser(): User {
        return new User({lastName: 'tra', firstName: 'yaya'});
    }
}
```
 when i tried to do :

**Comment by dsherret** [comment]
@yantrab that's because there's no function in that code. That file only has a class declaration in it and that class declaration has a constructor declaration and method declaration.

[See here](https://ts-ast-viewer.com/#code/AIYQ9gdgLgTmA28CmMAUAiAzmAtk9AlALABQSAHgA5gxQAEAxvAIaaZ0DKuS40ciKOgG9SdMY0iZYAVwZQaqSjACWAN2ZQkdbHg4pVyhkgBcnbnpgGjBYaPEBfO2OABxJFAzTMKQk7oBzdwBVbzQCUxDBERJxWLoYd2kYCDoIJAB3Oki0IRYpADlmPFMAclhmEoAaOgAzZRgCopM6EoBPZnaS+wIAbj9HEnsgA)

You will need to do code similar to what I posted [above](https://github.com/dsherret/ts-morph/issues/774#issuecomment-565178519).

**Comment by dsherret** [comment]
Do this:

```ts
const type = method.getReturnType().getText(method)
```

**Comment by yantrab** [comment]
thanks, it is perfect now!
