### ISSUE TITLE
[Question] Parse generic type

### ISSUE THREAD

**Issue by GrandSchtroumpf** [dsherret/ts-morph#810]
Hello,
I would like to extract the value "[button]" of the generic type below for example: 
```typescript
type Component<type, selector> = type;
definition class MyComponent {
  static selector: Component<string, '[button]'>;
}
```
I did : 
```typescript
const type = source.getClass('MyComponent').geStaticProperty('selector').getType();
type.getTypeArguments().map(a => a.getText()); // [ 'string' ]
```
It looks like `getTypeArguments` returns the value returned by the type and not the text.
Unfortunately I cannot use `type.getText()` and string manipulation because the realworld usecase is too complex.

I was looking for something like `type.isGeneric() ? type.getGeneric() : []` but did find anything that looks like that.
Thanks for the help :)

**Comment by dsherret** [comment]
@GrandSchtroumpf I get the following output instead:

```ts
type.getTypeArguments().map(a => a.getText()); // []
```

What's going on here is the TS compiler is "interning" the type to `string`. Try doing `type.getText()` and you will see it's a `string`. That's done for performance reasons in the compiler (I wish there was a way to disable it)... see [this answer](https://github.com/microsoft/TypeScript/issues/28197#issuecomment-434027046) from the TypeScript team.

In this scenario, instead of getting the type you can get the type node. Here's an example:

```ts
const project = new Project({ useInMemoryFileSystem: true });

const file = project.createSourceFile("file.ts", `type Component<type, selector> = type;
definition class MyComponent {
  static selector: Component<string, '[button]'>;
}`);

const propertyDec = file.getClassOrThrow('MyComponent').getStaticPropertyOrThrow('selector') as PropertyDeclaration;
const typeNode = propertyDec.getTypeNodeOrThrow() as TypeReferenceNode;

console.log(typeNode.getTypeArguments().map(a => a.getText())); // ['string', "'[button]'"]
```

**Comment by GrandSchtroumpf** [comment]
Amazing, thanks a lot !! So many kind of nodes ^^.
Why using TypeNode would work better than `getType` ?

**Comment by dsherret** [comment]
It's a common mistake due to somewhat bad naming, but I'm not sure what would be better. `getType()` returns the type from the type checker (shown in purple in the image below) and `getTypeNode()` returns the node from the AST (shown in blue).

![image](https://user-images.githubusercontent.com/1609021/80924943-270da480-8d5a-11ea-9a45-8f6281d5981d.png)
