### ISSUE TITLE
Question about a upgrade TS to version 3.9

### ISSUE THREAD

**Issue by szagi3891** [dsherret/ts-morph#816]
Can I ask for upgrading the TS version to 3.9?

The current version of morph does not want to work with the new TS.

```
Argument of type 'import("/home/grzegorz/Pulpit/Projekty/gpp-website3/node_modules/ts-morph/lib/ts-morph").Node<import("/home/grzegorz/Pulpit/Projekty/gpp-website3/node_modules/@ts-morph/common/node_modules/typescript/lib/typescript").Node>' is not assignable to parameter of type 'import("/home/grzegorz/Pulpit/Projekty/gpp-website3/node_modules/ts-morph/lib/ts-morph").Node<import("/home/grzegorz/Pulpit/Projekty/gpp-website3/node_modules/typescript/lib/typescript").Node>
```

**Comment by jasonkuhrt** [comment]
Thanks for the great project @dsherret. We're also awaiting it in https://github.com/graphql-nexus/nexus/pull/859. I'll try to find time in the coming days to help with a pull-request.

**Comment by dsherret** [comment]
Sorry, missed this until now and upgrading wasn't a priority since there wasn't much changes in TS 3.9.

Highly recommend using the `ts` export from `ts-morph` to ensure both your code and ts-morph are using the same compiler version so you don't run into trouble 🙂

```ts
import { ts } from "ts-morph";
```

I'll do a release for this soon.

**Comment by szagi3891** [comment]
Thank you very much. This completely solves my problem :)

**Comment by jasonkuhrt** [comment]
Hey @dsherret Maybe I missed something but IIUC 3.9 sin't supported yet. Can we keep this issue open until it is? Will make things easier to track on my side, if you don't mind!

**Comment by dsherret** [comment]
@jasonkuhrt I just forgot to merge `master` into `latest` (done now). Forgot I was trying that branching strategy for this project. I just double checked on npm and it's specifying 3.9.2.

**Comment by jasonkuhrt** [comment]
Ah awesome! Thanks

**Comment by jasonkuhrt** [comment]
FYI it turns out the issue was never ts-morph. If you're curious it looks like TS 3.9 has a regression. [TS Playground link](https://www.typescriptlang.org/play/index.html?ssl=53&ssc=2&pln=1&pc=1#code/PTAEHcHsCcGsGdQEsB2oDMA6AHAGlAGYCGSANoqhpgJwBQIoAkogC4AWSiRoARgK4BzZGizUA-PTAA5AKYAPPogAUKeYoBW8TDAEBKUABMZABxkojB0JDTtOhPigDGLJNaKkkLAJ61a306AA4jIsAIwAPLSgoACCoPIsZgZcKF64UaAAQvFyieYpaRkAwjl5yaAA5ARkidCoAhWgAD6VMEZ1KA20AHygALyxpUmIsDJekASgAMosfAQEGWJZQ-mgo+OTM3MEANoxALoZ0Utb83v7O5kXRYfR0QBcoKoAbjLQGY8vbwDcvv4yoGgoX6QRCEQqmVIkAauAqxkg8BY8AqsOqpFq9Qq3V8DBiKEg7DeoFsnUkTxkr2gEBgCGAUDgMgMZPAbC8Ej8XgCwRYACZItE4glhpVIdCURlskLVusJtNZmcDuloiUpeUqjU3pjmq1oO1MRlegNTrsDpdrocOQFoDyQdy+RCoTC4QikSj1ejNZ0sTiwHiCWwiSSBPhbIh6Qh8I4ofAZIiIADHJA+KRLAIQsTILwZAQYDIyQARSCxlAVFigIjOPjuUjlxwcCkApNUgSQdzEthJgRsP6cgHc9D8waqxAOsVK5bDtZjWXGnajhr7ccq3LC90Yr3aiptT1daKGuXbc5mnY3HtW9C2kID+du+GI5GojUdBrYyRvhiJOMGIgsIi+VC1MQjgAsaoAAN4ZAwOywPciLPvsjxEKkdwoahdwMOEAC0mGgAACnwLAuJ07Z2AG0AAtUcixqCYTCKAAAqUxUHQ0SigIjwQShUEwXB9QIeWyFoUJoAYdheEEURQihqAZEUUgVGINywKUIxzFoUcoB3kiHHqWhaLruxlREOKaHbs+jwVDwFQaQAvhkdk2UAA).
