### ISSUE TITLE
getPreEmitDiagnostics async

### ISSUE THREAD

**Issue by sguillia** [dsherret/ts-morph#864]
**Is your feature request related to a problem? Please describe.**

Hi!

Thanks for this lib

It seems like [`getPreEmitDiagnostics`](https://ts-morph.com/setup/diagnostics#diagnostics) takes quite some time to complete

**Describe the solution you'd like**

Is it possible to have it async?

**Describe alternatives you've considered**

- Ask `ts` upstream to have it async
- Spawn a new process much like vscode does with its LSP

By async I mean, not having it block the event loop

**Comment by dsherret** [comment]
`getPreEmitDiagnostics()` is almost entirely compiler api related. ts-morph essentially just calls `ts.getPreEmitDiagnostics(program)` so any change here would have to take place in the compiler API.

That said, I don't think it would be feasible to construct a program and then only have `ts.getPreEmitDiagnostics` run in a separate process or worker thread. You would need some way of getting the objects over (maybe some way with the incremental compiler since that offers some serialization/deserialization, but I'm not sure). What you could do, is tell the worker thread or process what files to use or filepaths with text, construct a new ts-morph project in that process/worker, run `getPreEmitDiagnostics()`, then send back the result to the main thread/process.
