### ISSUE TITLE
How to import Symbols into a SourceFile?

### ISSUE THREAD

**Issue by ikeyan** [dsherret/ts-morph#870]
I'm generating a .d.ts file that looks like this:

```typescript
export interface SyntaxKindNameToNodeMappings {
    SourceFile: SourceFile;
    ArrayBindingPattern: ArrayBindingPattern;
...
    BinaryExpression: BinaryExpression<ts.BinaryExpression>;
...
    SemicolonToken: Node<ts.Token<ts.SyntaxKind.SemicolonToken>>;
...
}
```

These types come from `PropertySignature`s of `ImplementedKindToNodeMappings` interface defined in this repository.

Then I need to import these types, but I don't know how to do so in general. Is there auto-import feature already?
(in this case I can hard-code the package locations, but I want the code to be general)
If I were to implement such a function myself, I have to know every corner cases of TS module resolution algorithm.

**Comment by dsherret** [comment]
In this case, since you know the types are coming from the `"ts-morph"` module in the named imports, you could just add an import declaration to the front of the file and import all the names you use from there.

Regarding auto imports, I think there is a `sourceFile.fixMissingImports()` method, but it might not always do what you'd like and it could be slower compared to just writing out your own import declaration.
