### ISSUE TITLE
Implement getProjectVersion on LanguageServiceHost

### ISSUE THREAD

**Issue by geremih** [dsherret/ts-morph#881]
Thanks for creating this awesome project!

**Is your feature request related to a problem? Please describe.**
I have a script that extracts some type information which was taking longer than I would have expected. On profiling the script the bottleneck appears to be calls to `synchronizeHostData` which are made by most calls to the language-service eg. [getDefinitionAtPosition](https://github.com/microsoft/TypeScript/blob/566faa7a01f3d483f032fda4777dae186eccbb19/src/services/services.ts#L1634).

`synchronizeHostData`  short-circuits if the host supports a `getProjectVersion` and the project version hasn't changed between calls. On implementating a dummy `getProjectVersion` the run time of my script went done from 150s to 10s.

Related: [original implementation in typescript](https://github.com/microsoft/TypeScript/pull/3131), [ts-loader PR that adds support for getProjectVersion](https://github.com/TypeStrong/ts-loader/pull/100)

**Describe the solution you'd like**
I'm up for contributing this myself if the plan sounds good to you. The general steps I had in mind are:
1. Add a version field on `TransactionalFileSystem` that is incremented on mutating operations (writeFile, deleteFile) etc.
2. (Optionally) Add a field to `ProjectOptions` to enable this behaviour to support the project being mutating outside ts-morph calls.

**Comment by dsherret** [comment]
@geremih Sorry for my delay—I've been super busy lately. This sounds like a good thing to do for sure!

I don't think this should be added to `TransactionalFileSystem` though because changes to a source file might not have hit the transactional file system yet.

I believe this would be super simple. I think the solution might be to just rename [`LanguageService#_resetProgram`](https://github.com/dsherret/ts-morph/blob/4ed90e0a4d69c3eeab703a7caad5514445d67820/packages/ts-morph/src/compiler/tools/LanguageService.ts#L66) to `LanguageService#_reset` then make it increment a value in there that's then returned in the `getProjectVersion()` function on the language service host. See how language service host is created [here](https://github.com/dsherret/ts-morph/blob/4ed90e0a4d69c3eeab703a7caad5514445d67820/packages/ts-morph/src/compiler/tools/LanguageService.ts#L41) and [here](https://github.com/dsherret/ts-morph/blob/4ed90e0a4d69c3eeab703a7caad5514445d67820/packages/common/src/compiler/createHosts.ts#L27). Let me know if I'm mistaken about anything.

If you'd like to implement this, then please go for it! 🙂

**Comment by geremih** [comment]
@dsherret Thanks for your comment. I've created a [PR](https://github.com/dsherret/ts-morph/pull/884/files) for this.
