### ISSUE TITLE
type.isNumber return false for optional parameter

### ISSUE THREAD

**Issue by yantrab** [dsherret/ts-morph#886]
**Describe the bug**

Version:latest

when you have for example - 
count?: number;

type.isNnumber() return false. it should return true, although the type is {number | undefined}, but i already know that is optional with param?.isOptional() function.

**Comment by dsherret** [comment]
Right now the `isNumber()` method will only return true when the type has a number type flag.

https://github.com/dsherret/ts-morph/blob/218d205a209809c423ff33cb5bd9af30681ad60c/packages/ts-morph/src/compiler/types/Type.ts#L341

The type `number | undefined` is technically a union type and not a number type, so that's why it returns false as intended. You can use `type.getNonNullableType().isNumber()` here.
