### ISSUE TITLE
Leading comment range on VariableDeclaration not including comments

### ISSUE THREAD

**Issue by stacey-gammon** [dsherret/ts-morph#901]
I have a test file that is not including comment ranges as I would expect.

Here is the code:

```ts
 it('test comment', () => {
  const project = new Project({ useInMemoryFileSystem: true });
  const file: SourceFile = project.createSourceFile(
    'plugin_a/public/index.ts',
    `
  /**
   * This is variable foo. It has a default value. And a comment!
   */
  export const foo: string = 'defaultval';
  `
  );

  file.getVariableDeclarations().forEach((v) => {
    if (v.getName() === 'foo') {
      console.log(`variable is ${v.getFullText()}`);
      expect(v.getLeadingCommentRanges().length).toBeGreaterThan(0);
    }
  });
});
```

The output is 

```
    variable is  foo: string = 'defaultval'
```

Can you help me understand why the comment is being dropped?

**Comment by dsherret** [comment]
Hi @stacey-gammon, the variable declaration doesn't have any leading comments because the comments are leading only on the parent variable statement.

See here for the range of the variable declaration:

![image](https://user-images.githubusercontent.com/1609021/101831779-7132e180-3b04-11eb-8cf2-0f2d2e59d4a3.png)

https://ts-ast-viewer.com/#code/PQKhCgAIUgVALAlgZ0iyA3AhgJ0VgIwBsBTSAMwHtKA6SASQBdJ4tUtIATE8rAVyLNsRPiToBBAHadIHAMaUAtopKTGAQighg4EgA8ADpRzMFk5MyqUAXJAt5JAc0gBeSAHJuvAY2HuANFCQwZSM8CQ4rh6h4TjuANxAA

If you go up to the variable statement then you should see be able to get its leading comment range:

```ts
v.getVariableStatementOrThrow().getLeadingCommentRanges()
```

That said, most likely in this scenario you'll want the JS doc nodes of the variable statement:

```ts
v.getVariableStatementOrThrow().getJsDocs()
```

![image](https://user-images.githubusercontent.com/1609021/101832057-d71f6900-3b04-11eb-9902-c871b9420954.png)

**Comment by stacey-gammon** [comment]
Awesome. Thanks so much for the quick reply and for the link to https://ts-ast-viewer.com - that is super helpful!
