### ISSUE TITLE
JsxText.getText() doesn't decode HTML entities

### ISSUE THREAD

**Issue by sschultze** [dsherret/ts-morph#918]
The `JsxText.getText()` method returns the inner text with undecoded HTML entities.

Version: 9.1.0

**To Reproduce**

Navigate the AST of the following code:

```
return <Localize>Sample &lgt; &gt; text.</Localize>;
```

The `JsxText.getText()` method returns `Sample &lt; &gt; text.`

**Expected behavior**

The `JsxText.getText()` method should return `Sample < > text.`

Which matches what the TypeScript compiler generates:

```
return React.createElement(Localize, null, "Sample < > text.");
```

And matches what the TypeScript AST viewer at https://www.typescriptlang.org/play shows when inspecting the `JsxText.text` property:

```
Sample < > text.
```

**Comment by sschultze** [comment]
The same applies to attribute values.

**Comment by dsherret** [comment]
This is expected behaviour and what's being returned here is just forwarding what the compiler API returns. The compiler API does not decode the string:

![image](https://user-images.githubusercontent.com/1609021/103553814-f8f9da80-4e7b-11eb-99e7-2190f577735d.png)

![image](https://user-images.githubusercontent.com/1609021/103553872-1038c800-4e7c-11eb-8277-c4afdeb7fbf0.png)

https://ts-ast-viewer.com/#code/MYewdgzgLgBLC8MA8BDAfAZRQWwA4BsBTGAMnwHMoBuUymqQgDygDokB6dKoA

I think the AST plugin on the TypeScript playground has a bug.

**Comment by sschultze** [comment]
Thank you for the research and explanation! Interesting. At least now I know that I can / should decode the string myself, without any fear that a future version will break this. (Hmm, I guess a unit test on my side would be a good idea.)
