### ISSUE TITLE
[Question] How disruptive are typescript upgrades?

### ISSUE THREAD

**Issue by stacey-gammon** [dsherret/ts-morph#922]
Over in the https://github.com/elastic/kibana repo, we are considering what tool to use for an automated API documentation system.  The options we are evaluating are this library, and api-extractor plus a custom api-documenter.  You can view the relevant RFC section [here](
 https://github.com/elastic/kibana/pull/86704/files#diff-67816cf4790fcb9ec86e393dcf88f3696ae80c744f563e944a8f5b8970a356dcR250). 

I have a few questions I was hoping you could help us with as we debate these two approaches.

One of the biggest concerns we have is how much maintenance will be required with the ts-morph approach. The question is two-fold:

1. How quickly are you able to support new typescript versions?
2. How often do you make breaking changes to your own APIs?

It looks like you've been able to keep up with new typescript versions pretty quickly. Would you accept upstream contributions if this was taking longer than expected?

We appreciate any guidance or information you can give us.  Thanks!

**Comment by dsherret** [comment]
Hi @stacey-gammon,

1. I usually get a release out on the day or within a few days of the release.
2. It was very agressive before, but not so much anymore as I'm more happy with the API. I think the API has stabilized a lot and mostly only do breaking changes now based on downstream breaking changes. That's not a guarantee though.

Yup, I would definitely accept contributions on upgrading TypeScript.

Since this is analysis only and you are concerned about performance, then it might be useful to come up with a test to see how much slower using ts-morph is compared to just the compiler API (I'm not sure what the numbers are). Also, perhaps using [@ts-morph/bootstrap](https://github.com/dsherret/ts-morph/tree/latest/packages/bootstrap) might be an option.
