### ISSUE TITLE
Ability to specify a specific typescript version

### ISSUE THREAD

**Issue by lramos15** [dsherret/ts-morph#932]
Hi! The VS Code team utilizes ts-morph to generate telemetry reports based on typed telemetry events (see https://github.com/microsoft/vscode-telemetry-extractor if interested). ts-morphs makes parsing Typescript's AST much easier, so thank you. I was wondering if there was a way for ts-morph to work with a peer dependency as we are trying to reduce the number of typescript version within VS Code (https://github.com/microsoft/vscode/issues/116503).

**Comment by dsherret** [comment]
It used to support a broad range of versions and it was hell. The ts compiler is unfortunately super unstable and does not follow semantic versioning so I always have this depend on a single minor version and sometimes even that isn't good enough. For example, this weekend I did a preliminary upgrade to TS 4.2 beta just to see how many breaking changes there would be and I found two breaking behaviour changes.

It looks like to reduce the bundle size in this case, it would need to support running on the development version of TypeScript. Is that correct? This most likely will lead to issues with this library not working properly.

Since the TS package takes up 60 MB, I'm thinking perhaps I could remove the package.json dependency on TypeScript and bundle typescript.js within ts-morph's package. It's 9MB or 5.5MB minified. Would that work?

**Comment by lramos15** [comment]
Bundling minified typescript.js within ts-morph's package sounds reasonable to me. I wouldn't expect many to be directly interfacing with the typescript package anyways since ts-morph abstracts a lot of that away. As you said, VS Code consistently dogfoods the latest Typescript versions and therefore 4.2 beta would be necessary.

**Comment by dsherret** [comment]
Yeah, ts-morph also re-exports the compiler api via `import { ts } from "ts-morph"` anyway so there would still be access to that. I think I'll do this.

**Comment by dsherret** [comment]
Ok, I opened #933. Going to close this one.
