### ISSUE TITLE
Argument of type 'ParameterDeclaration' is not assignable to parameter of type 'Node<Node>'

### ISSUE THREAD

**Issue by velut** [dsherret/ts-morph#936]
**Describe the bug**

After upgrading to version 10.0.0, nodes of type `ParameterDeclaration` are no longer comparable with the base `Node` type.

This affects the `Node.is...` type guards provided by ts-morph.

Version: 10.0.0
Typescript Version: 4.2.2

**To Reproduce**

```ts
import { Node, Project, ts } from 'ts-morph';

// Logs `4.2.2`
console.log(ts.version);

const project = new Project({ useInMemoryFileSystem: true });
const sourceFile = project.createSourceFile(
    'index.ts',
    `
    class Foo {
        constructor(readonly bar: string) {}
    }
    `
);

const foo = sourceFile.getClassOrThrow('Foo');
const ctor = foo.getConstructors()[0]!;
const bar = ctor.getParameterOrThrow('bar');

// With `ts-morph@10.0.0` this comparison is now a compiler error:
// `Argument of type 'ParameterDeclaration' is not assignable to parameter of type 'Node<Node>'.`
if (Node.isParameterDeclaration(bar)) {
    console.log('bar is a parameter declaration');
}
```

**Error reported by compiler**
```
Argument of type 'ParameterDeclaration' is not assignable to parameter of type 'Node<Node>'.
      The types returned by 'getParent()' are incompatible between these types.
        Type 'ConstructorDeclaration | CallSignatureDeclaration | ConstructSignatureDeclaration | ... 10 more ... | ArrowFunction' is not assignable to type 'Node<Node> | undefined'.
          Type 'ConstructorTypeNode' is missing the following properties from type 'Node<Node>': compilerNode, forget, forgetDescendants, wasForgotten, and 108 more.
```

**Expected behavior**

`ParameterDeclaration` should be comparable with `Node` as it happened on previous versions of ts-morph.

Thank you again for your time.

**Comment by dsherret** [comment]
Thanks for opening this! It's weird because looks like `ConstructorTypeNodeBase` is not in the output and for some reason the compiler is not producing a diagnostic for that not existing... (before publish, I have a script that checks the declaration file to see if it has any diagnostics)

https://github.com/dsherret/ts-morph/blob/15d94f9cfb865664542970ce08bdc8e4f163b571/packages/ts-morph/lib/ts-morph.d.ts#L8336

I'm looking into this now and will publish a release once fixed.

**Comment by dsherret** [comment]
Oh, I know why I didn't catch this... I just ran `npm publish` instead of `npm run dopublish`, which is my pre-publish script I'm supposed to run before releasing. My bad!

Fixed in https://github.com/dsherret/ts-morph/commit/e51eb0a3a3f41a51e025e5863b1a4c40e928d717

@velut thanks again for reporting!

10.0.1 should be up on npm within the next 5-10 minutes or so.

**Comment by velut** [comment]
Thanks for the quick fix!
