### ISSUE TITLE
GetAccessor.getReturnType() returns "any" instead of the actual type

### ISSUE THREAD

**Issue by ezolotko** [dsherret/ts-morph#952]
GetAccessor.getReturnType() returns "any" instead of the actual type

Version: 10.0.1

**To Reproduce**

```ts
import { Project } from 'ts-morph';

const project = new Project({
  tsConfigFilePath: '../code/tsconfig.json'
});

const sourceFiles = project.getSourceFiles();

sourceFiles.forEach(sourceFile => {
  sourceFile.getClasses().forEach(c => {
    c.getGetAccessors().forEach(a => {
        console.log(a.getReturnType().getText());
    });
  });
});

// --- while with the ../code/C.ts contains:

export class C {
    get p():X { }
}

```

**Actual behavior**
"any" printed to the console

**Expected behavior**
"X" printed to the console

Please download the the repro project from here: [morph-bug.zip](https://github.com/dsherret/ts-morph/files/6135569/morph-bug.zip)

**Comment by dsherret** [comment]
@ezolotko I will take a look at this later. Does `project.getPreEmitDiagnostics()` return anything?

**Comment by ezolotko** [comment]
@dsherret thank you. Yes, getPreEmitDiagnostics() returns "Cannot find name 'X'" error. Does this mean a type must be fully resolved by the compiler for ts-morph to be able to provide return type name information?
BTW, I resorted to the following workaround: `accessor.compilerNode.type?.getText()`

**Comment by dsherret** [comment]
Hey @ezolotko, I just had time to look at this and the reason this happens is because the `X` type does not exist in that project.

![image](https://user-images.githubusercontent.com/1609021/111052167-ca255500-8426-11eb-857d-03d5872a6b7c.png)

It's resolved when the `X` type is defined. This is because the `getReturnType()` method gets the return type from the type checker. If you just want to get it from the AST, the correct method to use is `getReturnTypeNode()`. This method will return the return type node if it exists and then you can do `.getText()` on it. So essentially `accessor.getReturnTypeNode()?.getText()` does `accessor.compilerNode.type?.getText(sourceFile.compilerNode)` behind the scenes and that's why your work around works. Hope that helps!

**Comment by ezolotko** [comment]
Thank you for the explanation. I will use `accessor.getReturnTypeNode()?.getText()` as you advised.
