### ISSUE TITLE
Recommended practice for use as a type checker?

### ISSUE THREAD

**Issue by Brian-McBride** [dsherret/ts-morph#954]
Hi. I have a build pipeline using esbuild. It is a fast transpiler, but more importantly for my current need is that it treeshakes NodeJS the best of all the various "packers"

It does not do type checking, however. I want to do a parallel process on my code with typescript just to do a typecheck. 

Would you feel that ts-morph is a good lib? And would you recommend getting all the files and just using the typeChecker method? Or is there a faster process I can just kick off without needing to flow into a callback on each file?

**Comment by rdsedmundo** [comment]
@dsherret this worked perfectly for me, as I wanted to write a custom module resolution before type-checking. I created a `custom-tsc` that resolves the paths properly before doing the type checking.

Running this script via CLI works wonders, the problem is VSCode which uses `tsc` directly so it reports false positives as it's not aware of the custom resolution. 

Do you think it's possible to force VSCode to use a hooked version of the compiler from `ts-morph`? I know that there's a configuration for that at the bottom-right, where you can set a config `typescript.tsdk` pointing to a custom TS (e.g `./node_modules/typescript/lib`, but I'm not sure what interface to do for the script to work.

I think I'd need to write a custom tsserver 🤔 .

Thank you very much for your work on this package!
